version: '3.8'

services:
  app:
    image: kijalxx/app
    ports:
      - "3000:3000"
    networks:
      - my_network

  micro1:
    image: kijalxx/micro1
    ports:
      - "8080:8080"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge