name: CI

on:
  push:
    branches:
      - main

jobs:
  build-book-database:
    name: Book Database Build
    runs-on: ubuntu-latest
##test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build bookDatabase
        working-directory: BookDatabase
        run: mvn package

      - name: Build bookDatabase Docker image
        working-directory: BookDatabase
        run: docker build -t kijalxx/book:latest .

  build-event-database:
    name: Event Database Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build eventDatabase
        working-directory: EventDatabase
        run: mvn package

      - name: Build eventDatabase Docker image
        working-directory: EventDatabase
        run: docker build -t kijalxx/event:latest .

  build-frontend:
    name: Frontend Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Build frontend
        working-directory: frontend
        run: npm run dev

      - name: Build frontend Docker image
        working-directory: frontend
        run: docker build -t kijalxx/app:latest .